baseURL = "https://fme-industry.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Formal Methods & Industry"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Formal Methods Europe INDUSTRY"
  homeMetaContent = "Formal Methods Europe Industry"
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Apr 1, 2019"
  codePenUser = "someUser"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.nav]]
    name = "Formal Methods"
    url = "/formal-methods/"
    weight = 3
#  [[menu.nav]]
#    name = "Industry Users"
#    url = "/industry-users/"
#    weight = 4
#  [[menu.nav]]
#    name = "Use Cases"
#    url = "/use-cases/"
#    weight = 5
  [[menu.nav]]
    name = "Useful Links"
    url = "/links/"
    weight = 6
#  [[menu.nav]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 7

